### PR TITLE
#40. Disable buttons when edit mode is enable.

### PR DESCRIPTION
**Pull request by LittleCuong**
I've created a new Fork and also check that this Fork has the latest changes as you suggested for me. Also, I checked that my code has the same formatting as yours.
This time my new branch has only 1 commit for the #40 issue. 
Once again, I sorry for my lack of professionalism!

### CODE REVIEW

**Comment by miljkovicjovan** [comment]
@LittleCuong Good job 😄! Don't worry about it we were all beginners until we tried!

**Review by miljkovicjovan — CHANGES_REQUESTED** [review]
I really like the solution it simple and it works nicely.
I have some feedback maybe make the borders of the buttons grey when the buttons are disabled.

Issues:
1. When on editMode the tooltip is being shown 
Screenshot 2023-11-03 at 14 53 21

2. When the task is edited the tooltip stays open and the button acts as if it's being hovered
Screenshot 2023-11-03 at 14 54 05

**Comment by LittleCuong** [comment]
> I really like the solution it simple and it works nicely. I have some feedback maybe make the borders of the buttons grey when the buttons are disabled.
> 
> Issues:
> 
> 1. When on editMode the tooltip is being shown
> 
> Screenshot 2023-11-03 at 14 53 21
> 2. When the task is edited the tooltip stays open and the button acts as if it's being hovered
> 
> Screenshot 2023-11-03 at 14 54 05

I am working on it and fix it as soon as possible.

**Comment by LittleCuong** [comment]
> I really like the solution it simple and it works nicely. I have some feedback maybe make the borders of the buttons grey when the buttons are disabled.
> 
> Issues:
> 
> 1. When on editMode the tooltip is being shown
> 
> Screenshot 2023-11-03 at 14 53 21
> 2. When the task is edited the tooltip stays open and the button acts as if it's being hovered
> 
> Screenshot 2023-11-03 at 14 54 05

I am working on it and fix it as soon as possible.

**Comment by LittleCuong** [comment]
I'll close this pull request and create a new one for you

**Pull request closed without merging**
