### PR TITLE
Add dateTime field to finished task

### PR DESCRIPTION
**Pull request by LittleCuong**
#29 Create dateTime field when finish a task

### CODE REVIEW

**Comment by miljkovicjovan** [comment]
Please make the createdAt from a single Date() object since it is the simplest to store the data. 
We do not format the data stored on the array but we will after when we are using it.

Please try to use the same formatting of code (2 space tabs instead of 4 space). If you go to Files changed tab (at the top of the screen) you will see that the whole file has been changed but that is not true. So please get the original formatting and make another commit.

**Review by miljkovicjovan — CHANGES_REQUESTED** [review]
Please make the createdAt from a single Date() object since it is the simplest to store the data.
We do not format the data stored on the array but we will after when we are using it.

Please try to use the same formatting of code (2 space tabs instead of 4 space). If you go to Files changed tab (at the top of the screen) you will see that the whole file has been changed but that is not true. So please get the original formatting and make another commit.

**Review by LittleCuong — COMMENTED** [review]
I made a change as your request. The data should be stored in an object so that it has both value name and createdAt

**Review by miljkovicjovan — CHANGES_REQUESTED** [review]
Great job, remove the comments and I'll approve you to merge it

**Comment by LittleCuong** [comment]
> Great job, remove the comments and I'll approve you to merge it

Done it bro

**Comment by miljkovicjovan** [comment]
@LittleCuong Let me fix the conflicts please do not commit anymore to this branch until it's merged. And in the future create separate branch for your work.

**Comment by LittleCuong** [comment]
> @LittleCuong Let me fix the conflicts please do not commit anymore to this branch until it's merged. And in the future create separate branch for your work.

Sorry for this inconvenience

**Review by miljkovicjovan — APPROVED** [review]
@LittleCuong Please in the future:
1. do not change the formatting of a file
2. do not go into other files that are not necessary for you task and change unnecessary things.
3. Create separate branches for each of your tasks so you can have different work in each of them and don't mix them.

**Comment by miljkovicjovan** [comment]
@all-contributors please add @LittleCuong for code

**Pull request merged**
